import csv
from pathlib import Path
import numpy as np

from sdapp.analysis.core.metrics import compute_frame_metrics, extract_primary_boundary, smooth_boundary_fft
from sdapp.host.config import EventCandidate, FrameRef
from sdapp.host.exporter import export_analysis

class FakeReader:
    def __init__(self, frames: list[np.ndarray], source_ext: str = ".tif"):
        self._frames = frames
        self._refs: list[FrameRef] = []
        for idx in range(len(frames)):
            self._refs.append(
                FrameRef(
                    frame_idx=idx,
                    source_path=Path(f"/fake/frame_{idx:04d}{source_ext}"),
                    page_index=None,
                    source_ext=source_ext,
                    frame_name=f"frame_{idx:04d}{source_ext}",
                )
            )

    def read_frame(self, frame_idx: int, use_cache: bool = True) -> np.ndarray:  # noqa: ARG002
        return self._frames[frame_idx]

    def get_frame_count(self) -> int:
        return len(self._frames)

    def get_stack_info(self):
        frame = np.asarray(self._frames[0]) if self._frames else np.zeros((0, 0), dtype=np.uint8)

        class _Info:
            frame_height = int(frame.shape[0]) if frame.ndim >= 2 else 0
            frame_width = int(frame.shape[1]) if frame.ndim >= 2 else 0

        return _Info()

    def get_frame_ref(self, frame_idx: int) -> FrameRef:
        return self._refs[frame_idx]

def _event(event_id: str, start: int, end: int, *, flags: dict | None = None) -> EventCandidate:
    return EventCandidate(
        event_id=event_id,
        start_idx=start,
        end_idx=end,
        duration_frames=end - start + 1,
        duration_sec=None,
        flags=dict(flags or {}),
        label=event_id,
    )

def test_round_trip_reproducibility(tmp_path: Path):
    # 1. Setup mock project state and frames
    # Creates frames of size 100x100
    frames = [np.zeros((100, 100), dtype=np.uint8) for _ in range(3)]
    reader = FakeReader(frames)

    # Pre-compute masks that would have been generated by SAM-2
    # Frame 0: 10x10 square
    mask_0 = np.zeros((100, 100), dtype=bool)
    mask_0[10:20, 10:20] = True
    
    # Frame 1: 15x15 square (grows)
    mask_1 = np.zeros((100, 100), dtype=bool)
    mask_1[10:25, 10:25] = True
    
    # Frame 2: 15x15 square (moves right)
    mask_2 = np.zeros((100, 100), dtype=bool)
    mask_2[10:25, 15:30] = True

    # 2. Sidecar simulates saved project state with the masks
    sidecar = {
        "evt_01": {
            "masks_committed": [
                mask_0.tolist(),
                mask_1.tolist(),
                mask_2.tolist()
            ],
            "metrics_settings": {
                "scale_px_per_mm": 100.0,
                "frames_per_sec": 2.0,
                "roi_mask": np.ones((100, 100), dtype=bool).tolist()
            }
        }
    }
    
    event_ids = ["evt_01"]
    events = [_event("evt_01", 0, 2)]

    # 3. Export
    export_analysis(
        reader=reader,
        events=events,
        output_dir=str(tmp_path),
        baseline_pre_frames=0,
        trace=None,
        selected_event_ids=event_ids,
        analysis_sidecar=sidecar,
        include_metric_area_recruited=True,
        include_metric_propagation_speed=True,
        propagation_gap_decision=lambda payload: "ignore",
    )
    
    # 4. Verify in-memory values match exported CSV exactly
    # Compute in-memory
    boundaries = [
        smooth_boundary_fft(extract_primary_boundary(mask_0)),
        smooth_boundary_fft(extract_primary_boundary(mask_1)),
        smooth_boundary_fft(extract_primary_boundary(mask_2))
    ]
    
    in_memory_metrics = compute_frame_metrics(boundaries)
    areas_px = in_memory_metrics["areas_px"]
    
    # Read from CSV
    csv_dir = tmp_path / "evt_01" / "metrics"
    
    # Area CSV
    area_csv_path = csv_dir / "area_recruited_evt_01.csv"
    assert area_csv_path.exists()
    
    with open(area_csv_path, newline='', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        rows = list(reader)
        
    assert len(rows) == 3
    # Check that in-memory metrics perfectly match the exported CSV (modulo scaling)
    # The scale is 100 px = 1mm, so 1 px = 0.01 mm, 1 px^2 = 0.0001 mm^2
    # mask 0 area should be approx 100 px -> 0.01 mm^2
    for i in range(3):
        expected_area_mm2 = areas_px[i] * ( (1/100.0) ** 2 )
        actual_area_mm2 = float(rows[i]["area_mm2"])
        assert np.isclose(expected_area_mm2, actual_area_mm2, rtol=1e-4)

    # Speed CSV
    speed_csv_path = csv_dir / "propagation_speed_evt_01.csv"
    assert speed_csv_path.exists()
    
    with open(speed_csv_path, newline='', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        rows = list(reader)
        
    assert len(rows) == 3
    # frame 0 speed is blank
    assert rows[0]["speed_um_per_sec"] == ""
    
    # frame 1 speed
    avg_dist_px = in_memory_metrics["avg_dist_px"]
    # 100 px = 1 mm = 1000 um -> 1 px = 10 um
    # sec_per_frame = 1/2.0 = 0.5s
    expected_speed_um_sec_1 = (avg_dist_px[1] * 10.0) / 0.5
    actual_speed_um_sec_1 = float(rows[1]["speed_um_per_sec"])
    assert np.isclose(expected_speed_um_sec_1, actual_speed_um_sec_1, rtol=1e-4)
